background_opacity: 0.9
# Colors (Solarized Dark)
#colors:
#  # Default colors
#  primary:
#    background: '0x002b36'
#    foreground: '0x839496'
#
#  # Normal colors
#  normal:
#    black:   '0x073642'
#    red:     '0xdc322f'
#    green:   '0x859900'
#    yellow:  '0xb58900'
#    blue:    '0x268bd2'
#    magenta: '0xd33682'
#    cyan:    '0x2aa198'
#    white:   '0xeee8d5'
#
#  # Bright colors
#  bright:
#    black:   '0x002b36'
#    red:     '0xcb4b16'
#    green:   '0x586e75'
#    yellow:  '0x657b83'
#    blue:    '0x839496'
#    magenta: '0x6c71c4'
#    cyan:    '0x93a1a1'
#    white:   '0xfdf6e3'
#
#colors:
#  # Default colors
#  primary:
#    background: '0x000000'
#    foreground: '0xc5c8f2'
#
#  # Normal colors
#  normal:
#    black:   '0x282a2e'
#    red:     '0xa54242'
#    green:   '0x8c9440'
#    yellow:  '0xde935f'
#    blue:    '0x5f819d'
#    magenta: '0x85678f'
#    cyan:    '0x5e8d87'
#    white:   '0x707880'
#
#  # Bright colors
#  bright:
#    black:   '0x373b41'
#    red:     '0xcc6666'
#    green:   '0xb5bd68'
#    yellow:  '0xf0c674'
#    blue:    '0x81a2be'
#    magenta: '0xb294bb'
#    cyan:    '0x8abeb7'
#    white:   '0xc5c8c6'

colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xc5c8f2'

  # Normal colors
  normal:
    black:   '0x282a2e'
    red:     '0xa54242'
    green:   '0x8c9440'
    yellow:  '0xde935f'
    blue:    '0x5f819d'
    magenta: '0x85678f'
    cyan:    '0x5e8d87'
    white:   '0x707880'

  # Bright colors
  bright:
    black:   '0x373b41'
    red:     '0xcc6666'
    green:   '0xb5bd68'
    yellow:  '0xf0c674'
    blue:    '0x81a2be'
    magenta: '0xb294bb'
    cyan:    '0x8abeb7'
    white:   '0xc5c8c6'

